config/routes.rb
Rails.application.routes.draw do
  devise_for :adminrails
  devise_for :users

  resources :users, only: [:show]
  
  resources :answer_votes

  resources :question_votes

  resources :answers

  resources :questions

  root 'questions#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :question_votes
  has_many :answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.reverse
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question_answer = Answer.new
    @answers = @question.answers.order(created_at: :desc).limit(5)
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:user_id, :title, :content)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def can_edit(entity)
    if (current_user.admin || current_user.moderator || entity.user_id == current_user.id)
      return true
    else
      return false
  end
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.slim
h1 Listing questions
table
  thead
    tr
      th User
      th Title
      th Content
      th colspan="3"

  tbody
    - @questions.each do |question| 
      tr
        td 
          =  question.user.name
        td
          = link_to question.title, question
        td 
          = question.content
br

- if current_user
  = link_to 'Ask Question', new_question_path 

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.slim
h2 = @question.title

.question-content 
  = @question.content

.question-footer.clearfix
  - if @question.user.avatar.url.present?
    = image_tag(@question.user.avatar.url, class: 'avatar-mini pull-left')

  .question-user-name.pull-left

  a.question-vote-icon.vote-icon.pull-right href="javascript:void(0)"
  input type="hidden" value=@question.id
  span.pull-right.votes-amount 
    = @question.question_votes.count

h3.answers-header
  span.inline-indent
    = @answers.count
  ' Answers

- @answers.each do |answer|
  .question-answer
    .answer-content
      = answer.content

    .answer-footer.clearfix
      - if answer.user.avatar.url.present?
        = image_tag(@question.user.avatar.url, class: 'avatar-mini pull-left')

      .question-user-name.pull-left
        = answer.user.name

      a.vote-icon.answer-vote-icon.pull-right href="javascript:void(0)"
      input type="hidden" value=@question.id
      span.pull-right.votes-amount 
        = answer.answer_votes.count

- if current_user
  = form_for(@question_answer) do |f|
    = f.hidden_field :question_id, :value => @question.id
    = f.text_area :content
    = f.submit