config/routes.rb
Rails.application.routes.draw do
  devise_for :adminrails
  devise_for :users

  resources :users, only: [:show]
  
  resources :answer_votes

  resources :question_votes

  resources :answers

  resources :questions

  root 'questions#index'

end

app/models/answer_vote.rb
class AnswerVote < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user
end

app/controllers/answer_votes_controller.rb
class AnswerVotesController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  # POST /answer_votes.json
  def create
    if AnswerVote.exists?(user_id: current_user.id, answer_id: params[:answerId])
      render json: { message: 'The vote already exists' }, status: :unprocessable_entity
      return
    end
      
    @vote = AnswerVote.new
    @vote.user_id = current_user.id
    @vote.answer_id = params[:qanswerId]

    respond_to do |format|
      if @vote.save
        format.json { head :no_content }
      else
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer_vote
      @answer_vote = AnswerVote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_vote_params
      params.require(:answer_vote).permit(:answerId, :user_id)
    end
end

app/helpers/answer_votes_helper.rb
module AnswerVotesHelper
end

app/views/answer_votes/_form.html.erb
<%= form_for(@answer_vote) do |f| %>
  <% if @answer_vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer_vote.errors.count, "error") %> prohibited this answer_vote from being saved:</h2>

      <ul>
      <% @answer_vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answerId %><br>
    <%= f.number_field :answerId %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answer_votes/edit.html.erb
<h1>Editing answer_vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer_vote %> |
<%= link_to 'Back', answer_votes_path %>

app/views/answer_votes/index.html.erb
<h1>Listing answer_votes</h1>

<table>
  <thead>
    <tr>
      <th>Answerid</th>
      <th>user_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answer_votes.each do |answer_vote| %>
      <tr>
        <td><%= answer_vote.answerId %></td>
        <td><%= answer_vote.user_id %></td>
        <td><%= link_to 'Show', answer_vote %></td>
        <td><%= link_to 'Edit', edit_answer_vote_path(answer_vote) %></td>
        <td><%= link_to 'Destroy', answer_vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer vote', new_answer_vote_path %>

app/views/answer_votes/new.html.erb
<h1>New answer_vote</h1>

<%= render 'form' %>

<%= link_to 'Back', answer_votes_path %>

app/views/answer_votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Answerid:</strong>
  <%= @answer_vote.answerId %>
</p>

<p>
  <strong>user_id:</strong>
  <%= @answer_vote.user_id %>
</p>

<%= link_to 'Edit', edit_answer_vote_path(@answer_vote) %> |
<%= link_to 'Back', answer_votes_path %>